[package]
name = "ray-tracing-in-one-weekend"
version = "0.1.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
edition = "2018"

[features]
default = ["lambertian"]
lambertian = []

[dependencies]
rand = "0.7"

[dev-dependencies]
float_eq = "0.4"
