[package]
name = "ray-tracing-in-one-weekend"
version = "0.1.1"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]
edition = "2018"

[dependencies]
console = "0.11"
indicatif = { version = "0.15", features = ["rayon"] }
rand = "0.7"
rayon = "1.3"

[dev-dependencies]
float_eq = "0.4"
